### ISSUE TITLE
Documentation URL is hard-coded

### ISSUE THREAD

**Issue by alfredbuehler** [aljawaid/ApplicationBranding#10]
![image](https://user-images.githubusercontent.com/2079289/227185912-1de26d0c-3893-4869-a534-218d6c9d7236.png)

You should use the definition in the file constants.php:
```php
// Documentation URL
defined('DOCUMENTATION_URL_PATTERN') or define('DOCUMENTATION_URL_PATTERN', getenv('DOCUMENTATION_URL_PATTERN') ?: 'https://docs.kanboard.org/v1/user/%s');
```

**Comment by aljawaid** [comment]
Thanks for pointing that out, I will work on it
