### ISSUE TITLE
Ignore `localhost` as IP Address

### ISSUE THREAD

**Issue by aljawaid** [aljawaid/ApplicationBranding#5]
**Issue:**
> On the defaut login screen, at the very bottom of the login panel, I see “Your IP: 127.0.0.1”. I host kanboard behind a reverse proxy, so the web server only listens on 127.0.0.1/localhost

**Forum Post**
https://kanboard.discourse.group/t/new-plugin-applicationbranding/2592/2?u=aljawaid

**Comment by axb21** [comment]
Here's a screenshot of what my login screen looks like, with the 127.0.0.1 at the bttomL
![2023-01-30 11 14 58 www bucci onl 8a947bd2e29e](https://user-images.githubusercontent.com/3464572/215534464-f9b87dea-87ff-4a24-acce-ac3cfc386c0d.png)
