### ISSUE TITLE
2FA Page Styling is Inconsistent with Plugin

### ISSUE THREAD

**Issue by aljawaid** [aljawaid/ApplicationBranding#6]
**Issue:**
> The 2fa page is not branded in the same way as the login page

**Forum Post**
https://kanboard.discourse.group/t/new-plugin-applicationbranding/2592/2?u=aljawaid

- [x] Add URL Rewrite
- [x] Revamp 2FA Code Check page

**Comment by aljawaid** [comment]
> There are no icons or anything on that page--I cropped it but there's not much more to it than what's in the crop.

@axb21 Does it show a completely new page for the 2FA or is it part of the login form? Just like the captcha becomes part of the login form.  I'm just trying to understand whether I should make it like the password reset page, so it is consistent, or whether i need to fit it into the login form.

**Comment by axb21** [comment]
> @axb21 Does it show a completely new page for the 2FA or is it part of the login form? Just like the captcha becomes part of the login form. I'm just trying to understand whether I should make it like the password reset page, so it is consistent, or whether i need to fit it into the login form.

It's a brand new page. The query string is `controller=TwoFactorController&action=code`

**Comment by aljawaid** [comment]
> Hi @aljawaid , here's a screenshot depicting what I mean by that: ![2023-01-30 11 15 28 www bucci onl 12a8f8e85790](https://user-images.githubusercontent.com/3464572/215534019-f8f54618-0c0f-44f6-bf8a-c732532fe453.png)
> 
> There are no icons or anything on that page--I cropped it but there's not much more to it than what's in the crop.

![image](https://user-images.githubusercontent.com/10233708/215656188-15b67e4c-b7e8-4c7e-867e-2d53c7956aff.png)
I see what you mean.... **I am horrified** that this is deemed as an acceptable core template.

**Comment by axb21** [comment]
> I see what you mean.... **I am horrified** that this is deemed as an acceptable core template.

I'm no frontend developer or designer, but yeah, this is clunky as heck. It seems to me that it could be part of the login screen the way captchas are, as you suggested before, and that'd be much more immediate and intuitive.

**Comment by aljawaid** [comment]
I don't think I will be able to make it part of the login screen because of the way it is coded. IF I break the function, I won't know how to fix it so better I dont touch it.  I plan to redesign the whole security check page to be the same as the login and password reset page styling so there is consistency within the plugin for those who use it.  Ive already done the url rewrite, but the redesign I will start on tonight.

**Comment by aljawaid** [comment]
@axb21 how does this look?
![image](https://user-images.githubusercontent.com/10233708/216048635-cbc364b6-fbce-41ec-a673-f0ead93b6018.png)

**Comment by axb21** [comment]
Heck yeah, that looks so much better. That's what I'd expect to see when it came time to enter the 2fa code.

**Comment by aljawaid** [comment]
> Heck yeah, that looks so much better. That's what I'd expect to see when it came time to enter the 2fa code.

the text and design is loosely based on the github style but i think it fits in nicely with the rest of the plugin.  I will push the changes tonight and release a new version soon

**Comment by aljawaid** [comment]
what i found very annoying is that there was no way to cancel login.  if you dont enter the code, open the browser a few hours later, you dont even get back to the login screen... just the code check... i fixed it with a logout button

**Comment by axb21** [comment]
Oh wow that's so weird. I never went through that flow--always ended up logging in. 

It sounds to me like that whole process needed some love. I'm glad you're looking into it.
